[package]
name = "hashing"
version = "0.1.0"
edition = "2024"

[dependencies]
console_log = "1.0.0"
log = "0.4.26"
sha1 = "0.10.6"
sha2 = "0.10.8"
wasm-bindgen = "0.2.100"

[lib]
crate-type = ["cdylib"]
