# See these links for documentation 
# https://docs.green-coding.io/docs/measuring/usage-scenario/
# https://github.com/green-coding-solutions/simple-example-application?tab=readme-ov-file
---
name: Green coding with Rust demo
author: Sofush & András Ács Pedersen <anac@zealand.dk>  
description: This is a demonstration usage scenario for testing a basci web application

networks:
  name: no-network-for-now

services:
  hashing-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: hashing-app
    #command: ["npm", "run", "serve"]

flow: 
  - name: Hashing test
    container: hashing-app
    commands:
      - type: console
        command: npm run serve
        note: Starting service
